// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  main: [{ type: "autogenerated", dirName: "." }],
  examples: [
    {
      type: "category",
      label: "Components",
      items: [{ type: "autogenerated", dirName: "components" }],
    },
    {
      type: "category",
      label: "Page",
      items: [{ type: "link", label: "Page", href: "/page-example" }],
    },
    {
      type: "link",
      label: "NoneBot",
      href: "https://nonebot.dev",
    },
  ],
};

module.exports = sidebars;
